version: "2"
services:

  app:
    build: ./app
    links:
      - storage

  nginx:
    build: ./nginx
    links:
      - app
    ports:
      - "80:80"

  storage:
    image: postgres:9.6.10
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./storage:/docker-entrypoint-initdb.d/:ro
