Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.hostname = "ERTK"  # имя гостевой ОС
  config.vm.define "ERTK"  # имя бокса в vagrant

  config.vm.network "public_network", ip: "192.168.1.100"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    vb.name = "ertk"  # имя виртуальной машины в VirtualBox

  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  end

end
