---

- name: Build and start containers
  hosts: localhost
  connection: local
  remote_user: root

  tasks:
  - name: Build App Image
    docker_image:
      path: ../app
      name: ertk_app
      tag: latest

  - name: Build nginx Image
    docker_image:
      path: ../nginx
      name: ertk_nginx
      tag: latest

  - name: Create storage container
    docker_container:
      name: ertk_storage
      image: postgres:9.6.10
      volumes:
        - ../storage:/docker-entrypoint-initdb.d/:ro

  - name: Create App Container
    docker_container:
      name: ertk_app
      image: ertk_app
      links:
        - storage
      privileged: true

  - name: Create nginx Container
    docker_container:
      name: ertk_nginx
      image: ertk_nginx
      ports:
        - "80:80"
      links:
        - app
      privileged: true