---

- name: Build and start containers
  hosts: localhost
  connection: local
  become: yes

  vars:
    app_servers_count: 4

  tasks:

  - name: Install python-docker on Red Hat based distribution
    yum:
      name: python-docker
      enablerepo: extras
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install python-docker on Debian based distribution
    apt:
      name: python-docker
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Build APP Image
    docker_image:
      path: ../app
      name: ertk_app
      tag: latest

  - name: Build NGINX Image
    docker_image:
      path: ../nginx
      name: ertk_nginx
      tag: latest

  - name: Create network
    docker_network:
      name: ertk_network

  - name: Create STORAGE container
    docker_container:
      name: ertk_storage
      image: postgres:9.6.10
      networks:
        - name: ertk_network
      env:
        POSTGRES_PASSWORD: 12345
      volumes:
        - ../storage/:/docker-entrypoint-initdb.d/:ro

  - name: Create APP container
    docker_container:
      name: "ertk_app{{ item }}"
      recreate: yes
      image: ertk_app
      command: python app.py
      networks:
        - name: ertk_network
    with_sequence: count={{ app_servers_count }}

  - name: Create NGINX container
    docker_container:
      name: ertk_nginx
      image: ertk_nginx
      ports:
        - 80:80
      networks:
        - name: ertk_network

  - name: check container status
    command: docker ps
    register: result

  - debug:
      var: result.stdout
